export type ChatIndex = number
export type EbookReaderStatus = 'idle' | 'capturing' | 'paginating' | 'ready' | 'error'
export type ReaderSpeakerRole = 'user' | 'char' | 'unknown'
export type ReaderHeaderInfo = { chatIndex: ChatIndex; role: ReaderSpeakerRole; name?: string; thumbnailUrl?: string }
export type ReaderContentButtonDescriptor = { chatIndex: ChatIndex; ordinal: number; selector: string }
export type CapturedReaderMessage = { chatIndex: ChatIndex; chatId?: string; html: string; headerInfo: ReaderHeaderInfo; contentHash: string; contentButtons?: ReaderContentButtonDescriptor[] }
export type CaptureChunkResult = { requestedIndices: ChatIndex[]; capturedMessages: CapturedReaderMessage[]; missingIndices: ChatIndex[]; partial: boolean; startIndex: ChatIndex; endIndex: ChatIndex }
export type ReaderPageOverflowMode = 'scrollable'
export type ReaderPage = { pageIndex: number; chatPageIndex: number; chatIndex: ChatIndex; headerInfo: ReaderHeaderInfo; html: string; overflowMode?: ReaderPageOverflowMode }
export type ReaderAction = 'copy' | 'tts' | 'bookmark' | 'translate' | 'reroll' | 'unreroll' | 'remove' | 'jumpToOriginal' | 'editInOriginal'
